/* ============================================================================
   PICKS DATA FILE â€” generated by admin.html on 2026-09-09T00:09:58.100Z
   Edit via admin.html (click grid), NOT by hand. Then: git add picks.js ; git commit ; git push
   PLAYERS: Nick, Clyde, Chet, Henry, Riley, Bobby
   ============================================================================ */
window.PICKS = {
  week: 1,
  season: 2026,
  players: ["Nick", "Clyde", "Chet", "Henry", "Riley", "Bobby"],

  games: [
    { team1: "NE", team2: "SEA", picks: { Nick: "NE", Clyde: "SEA", Chet: "SEA", Henry: "NE", Riley: "SEA", Bobby: "SEA" } },
    { team1: "SF", team2: "LAR", picks: { Nick: "SF", Clyde: "LAR", Chet: "LAR", Henry: "LAR", Riley: "LAR", Bobby: "LAR" } },
    { team1: "TB", team2: "CIN", picks: { Nick: "CIN", Clyde: "CIN", Chet: "CIN", Henry: "CIN", Riley: "TB", Bobby: "CIN" } },
    { team1: "NO", team2: "DET", picks: { Nick: "DET", Clyde: "NO", Chet: "DET", Henry: "DET", Riley: "DET", Bobby: "DET" } },
    { team1: "NYJ", team2: "TEN", picks: { Nick: "NYJ", Clyde: "NYJ", Chet: "TEN", Henry: "TEN", Riley: "TEN", Bobby: "NYJ" } },
    { team1: "BAL", team2: "IND", picks: { Nick: "BAL", Clyde: "BAL", Chet: "BAL", Henry: "IND", Riley: "BAL", Bobby: "BAL" } },
    { team1: "ATL", team2: "PIT", picks: { Nick: "PIT", Clyde: "ATL", Chet: "PIT", Henry: "PIT", Riley: "PIT", Bobby: "PIT" } },
    { team1: "CHI", team2: "CAR", picks: { Nick: "CHI", Clyde: "CHI", Chet: "CHI", Henry: "CHI", Riley: "CHI", Bobby: "CHI" } },
    { team1: "CLE", team2: "JAX", picks: { Nick: "JAX", Clyde: "JAX", Chet: "JAX", Henry: "JAX", Riley: "JAX", Bobby: "JAX" } },
    { team1: "BUF", team2: "HOU", picks: { Nick: "HOU", Clyde: "BUF", Chet: "BUF", Henry: "BUF", Riley: "HOU", Bobby: "HOU" } },
    { team1: "MIA", team2: "LV", picks: { Nick: "LV", Clyde: "MIA", Chet: "MIA", Henry: "LV", Riley: "LV", Bobby: "LV" } },
    { team1: "GB", team2: "MIN", picks: { Nick: "MIN", Clyde: "MIN", Chet: "MIN", Henry: "MIN", Riley: "MIN", Bobby: "MIN" } },
    { team1: "WSH", team2: "PHI", picks: { Nick: "PHI", Clyde: "PHI", Chet: "PHI", Henry: "PHI", Riley: "PHI", Bobby: "PHI" } },
    { team1: "ARI", team2: "LAC", picks: { Nick: "LAC", Clyde: "LAC", Chet: "LAC", Henry: "LAC", Riley: "LAC", Bobby: "LAC" } },
    { team1: "DAL", team2: "NYG", picks: { Nick: "DAL", Clyde: "DAL", Chet: "NYG", Henry: "DAL", Riley: "DAL", Bobby: "DAL" } },
    { team1: "DEN", team2: "KC", picks: { Nick: "DEN", Clyde: "DEN", Chet: "DEN", Henry: "DEN", Riley: "DEN", Bobby: "KC" } },
  ],

  tiebreakerGame: { team1: "DEN", team2: "KC" },
  tiebreaker: { Nick: 43, Clyde: 47, Chet: 50, Henry: 42, Riley: 49, Bobby: 40 },

  // Edit history (receipt of what was entered and when). Appended each time you generate.
  _editLog: [
    "2026-09-09T00:09:58.100Z â€” Week 1 2026 entered via admin grid",
  ],
};
