/* ============================================================================
   PICKS DATA FILE — generated by admin.html on 2026-09-16T00:44:24.367Z
   Edit via admin.html (click grid), NOT by hand. Then: git add picks.js ; git commit ; git push
   PLAYERS: Nick, Clyde, Chet, Henry, Riley, Bobby
   ============================================================================ */
window.PICKS = {
  week: 2,
  season: 2026,

  players: ["Nick", "Clyde", "Chet", "Henry", "Riley", "Bobby"],

  games: [
    { team1: "DET", team2: "BUF", picks: { Nick: "BUF", Clyde: "BUF", Chet: "BUF", Henry: "BUF", Riley: "BUF", Bobby: "BUF" } },
    { team1: "CAR", team2: "ATL", picks: { Nick: "CAR", Clyde: "CAR", Chet: "CAR", Henry: "CAR", Riley: "CAR", Bobby: "CAR" } },
    { team1: "MIN", team2: "CHI", picks: { Nick: "MIN", Clyde: "CHI", Chet: "MIN", Henry: "MIN", Riley: "MIN", Bobby: "CHI" } },
    { team1: "PHI", team2: "TEN", picks: { Nick: "PHI", Clyde: "PHI", Chet: "PHI", Henry: "PHI", Riley: "PHI", Bobby: "PHI" } },
    { team1: "PIT", team2: "NE", picks: { Nick: "NE", Clyde: "NE", Chet: "NE", Henry: "NE", Riley: "NE", Bobby: "PIT" } },
    { team1: "GB", team2: "NYJ", picks: { Nick: "GB", Clyde: "GB", Chet: "NYJ", Henry: "GB", Riley: "GB", Bobby: "GB" } },
    { team1: "CLE", team2: "TB", picks: { Nick: "TB", Clyde: "TB", Chet: "TB", Henry: "TB", Riley: "TB", Bobby: "TB" } },
    { team1: "NO", team2: "BAL", picks: { Nick: "BAL", Clyde: "BAL", Chet: "BAL", Henry: "BAL", Riley: "BAL", Bobby: "BAL" } },
    { team1: "CIN", team2: "HOU", picks: { Nick: "HOU", Clyde: "HOU", Chet: "HOU", Henry: "CIN", Riley: "HOU", Bobby: "HOU" } },
    { team1: "JAX", team2: "DEN", picks: { Nick: "JAX", Clyde: "JAX", Chet: "JAX", Henry: "JAX", Riley: "JAX", Bobby: "JAX" } },
    { team1: "LV", team2: "LAC", picks: { Nick: "LV", Clyde: "LAC", Chet: "LV", Henry: "LAC", Riley: "LAC", Bobby: "LAC" } },
    { team1: "WSH", team2: "DAL", picks: { Nick: "WSH", Clyde: "DAL", Chet: "WSH", Henry: "DAL", Riley: "DAL", Bobby: "DAL" } },
    { team1: "SEA", team2: "ARI", picks: { Nick: "ARI", Clyde: "SEA", Chet: "ARI", Henry: "SEA", Riley: "SEA", Bobby: "SEA" } },
    { team1: "MIA", team2: "SF", picks: { Nick: "SF", Clyde: "SF", Chet: "SF", Henry: "SF", Riley: "SF", Bobby: "SF" } },
    { team1: "IND", team2: "KC", picks: { Nick: "KC", Clyde: "KC", Chet: "KC", Henry: "KC", Riley: "KC", Bobby: "KC" } },
    { team1: "NYG", team2: "LAR", picks: { Nick: "NYG", Clyde: "LAR", Chet: "LAR", Henry: "LAR", Riley: "LAR", Bobby: "LAR" } },
  ],

  tiebreakerGame: { team1: "NYG", team2: "LAR" },
  tiebreaker: { Nick: 55, Clyde: 54, Chet: 45, Henry: 50, Riley: 48, Bobby: 56 },

  // Edit history (receipt of what was entered and when). Appended each time you generate.
  _editLog: [
    "2026-09-16T00:44:24.367Z — Week 2 2026 entered via admin grid",
  ],
};
